version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "estamos en la fase previa a la construcción"
      - echo $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo "estamos en el bloque de construcción"
      - echo "vamos a ejecutar algunos tests"
      - pwd
      - ls
      - cat lambda_function.py
  post_build:
    commands:
      - echo "estamos en la fase de postconstrucción"
artifacts:
  files:
    - 'lambda_function.py'
    - 'deploy_lambda.sh'